services:
  - type: web
    name: pingpong-booking
    env: node
    buildCommand: npm install
    startCommand: node server.js
    rootDir: Express
    plan: free
    envVars:
      - key: NODE_ENV
        value: production

